### ISSUE TITLE
Request to remove 357 parts of this repo

### ISSUE THREAD

**Issue by inducer** [DeathByTape/UofI_undergrad#1]
Hi, UIUC sci comp prof here. Could you please delete the 357 parts of this repository? While we're not using those same assignments any more right now, we may reuse some parts of them in the future. As such, having solution code for them available online provides a temptation to cheat, and it makes it hard for us to determine whether students' submissions are actually their own work.

Thanks for considering this request,
Andreas

**Comment by DennisMcWherter** [comment]
Sorry for the delay; I just saw this. I will look into removing this section soon. Good luck with the semester!

**Comment by DennisMcWherter** [comment]
Hi @inducer, the code has been removed and I have cleared the commit history of any traces of it. Please confirm this has been done as you expect.

**Comment by inducer** [comment]
Fantastic, thank you very much!
